# Generated by Django 5.0.7 on 2025-03-10 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.TextField(max_length=255)),
                ('city', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=20)),
                ('rooms', models.TextField(max_length=1)),
                ('bathrooms', models.TextField(max_length=1)),
                ('metters', models.TextField(max_length=1)),
                ('price', models.TextField(max_length=5)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='tenants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Names', models.TextField(max_length=255)),
                ('Surnames', models.TextField(max_length=50)),
                ('Age', models.TextField(max_length=20)),
                ('Email', models.TextField(max_length=1)),
                ('Worktimes', models.TextField(max_length=1)),
                ('Schedules', models.TextField(max_length=1)),
                ('Studies_level', models.TextField(max_length=5)),
                ('Pets', models.TextField(max_length=150)),
                ('Cookies', models.TextField(max_length=1)),
                ('Sport', models.TextField(max_length=1)),
                ('Smoking', models.TextField(max_length=5)),
                ('Organized', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='lessor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('telephone', models.TextField(max_length=9)),
                ('email', models.TextField(max_length=50)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.rooms')),
            ],
        ),
    ]
