# Generated by Django 5.0.7 on 2025-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='bathrooms',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='metters',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='rooms',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='Cookies',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='Email',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='Schedules',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='Smoking',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='Sport',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='Studies_level',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='Worktimes',
            field=models.TextField(max_length=100),
        ),
    ]
