# Generated by Django 5.0.7 on 2025-03-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_rooms_bathrooms_alter_rooms_metters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenants',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='Cookies',
            new_name='cookies',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='Names',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='Organized',
            new_name='organized',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='Pets',
            new_name='pets',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='Schedules',
            new_name='schedules',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='Smoking',
            new_name='smoking',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='Studies_level',
            new_name='studies_level',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='Surnames',
            new_name='surnames',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='Worktimes',
            new_name='worktimes',
        ),
    ]
