# Generated by Django 5.0.7 on 2025-03-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_rename_age_tenants_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenants',
            old_name='Sport',
            new_name='sport',
        ),
        migrations.AddField(
            model_name='tenants',
            name='read',
            field=models.TextField(default='Yes', max_length=20),
            preserve_default=False,
        ),
    ]
